import Background from "./Background";
import Elements from "./Elements";
import Text from "./Text";
import Templates from "./Templates";
import Delete from "./Delete";
import Locked from "./Locked";
import UnLocked from "./Unlocked";
import Bold from "./Bold";
import Italic from "./Italic";
import TextColor from "./TextColor";
import FillColor from "./FillColor";
import Photos from "./Photos";
import TextAlignCenter from "./TextAlignCenter";
import TextAlignRight from "./TextAlignRight";
import TextAlignLeft from "./TextAlignLeft";
import TextAlignJustify from "./TextAlignJustify";
import Underline from "./Underline";
import Opacity from "./Opacity.";
import Duplicate from "./Duplicate";
import ToFront from "./ToFront";
import Forward from "./Forward";
import ToBack from "./ToBack";
import Backward from "./Backward";
import Undo from "./Undo";
import Redo from "./Redo";
import TimeFast from "./TimeFast";
import Search from "./Search";
import Edit from "./Edit";
class Icons {}
Icons.Background = Background;
Icons.Elements = Elements;
Icons.Text = Text;
Icons.Templates = Templates;
Icons.Delete = Delete;
Icons.Locked = Locked;
Icons.UnLocked = UnLocked;
Icons.Bold = Bold;
Icons.Italic = Italic;
Icons.TextColor = TextColor;
Icons.FillColor = FillColor;
Icons.Photos = Photos;
Icons.TextAlignRight = TextAlignRight;
Icons.TextAlignCenter = TextAlignCenter;
Icons.TextAlignLeft = TextAlignLeft;
Icons.TextAlignJustify = TextAlignJustify;
Icons.Underline = Underline;
Icons.Opacity = Opacity;
Icons.Duplicate = Duplicate;
Icons.ToFront = ToFront;
Icons.Forward = Forward;
Icons.ToBack = ToBack;
Icons.Backward = Backward;
Icons.Undo = Undo;
Icons.Redo = Redo;
Icons.TimeFast = TimeFast;
Icons.Search = Search;
Icons.Edit = Edit;
export default Icons;
